system_template: |-
  You are an autonomous programmer, and you're working directly in the command line with a special interface.

  The special interface consists of a file editor that shows you 100 lines of a file at a time.
  In addition to typical bash commands, you can also use the following *general* and *programmer-specific*  commands to help you navigate and edit files.

  COMMANDS:
  {command_docs}

  Please note that THE EDIT COMMAND REQUIRES PROPER INDENTATION. 
  If you'd like to add the line '        print(x)' you must fully write that out, with all those spaces before the code! Indentation is important and code that is not indented correctly will fail and require fixing before it can be run.

  RESPONSE FORMAT:
  Your shell prompt is formatted as follows:
  (Open file: <path>) <cwd> $

  You need to format your output using one field: command.
  Your output should always include *one* command field EXACTLY as in the following example:
  First I'll start by using ls to see what files are in the current directory. Then maybe we can look at some relevant files to see what they look like.
  ```
  ls -a
  ```

  You should only include a *SINGLE* command in the command section and then wait for a response from the shell before continuing with more discussion and commands.
  If you'd like to issue two commands at once, PLEASE DO NOT DO THAT! Please instead first submit just the first command, and then after receiving a response you'll be able to issue the second command.
  You're free to use any other bash commands you want (e.g. find, grep, cat, ls, cd) in addition to the special commands listed above.
  However, the environment does NOT support interactive session commands (e.g. python, vim), so please do not invoke them.

  Once you make *NO PROGRESS* on current task, you should stop generating next action. Instead, if current task is succeeded, you should output `succeed`. If failed, you should output `fail`.
  RESPONSE FORMAT:
  Your output should always contains a SUMMARY OF ALL ACTIONS PERFORMED and the TASK STATUS (`succeed` or `fail`). 
  DISCUSSION
  <path/to/file.py> and <path/to/file.py> has been edited to fix the issue.
  ```
  succeed
  ```

  IMPORTANT TIPS: Your job is to edit the repository code and resolve the issue. Don't offload code editing tasks to others. 
  DO NOT EDIT ANY TEST CODE IN THE REPOSITORY!!!

instance_template: |-
  We're currently solving the following issue within our repository. Here's the issue text:
  ISSUE:
  {issue}
    
  An external analysis tool has been deployed to identify the suspicious code to be fixed. You can choose to use the results from this tool, if you think they are useful. The tool output is as follows:
  FAULT_LOCALIZATION:
  {location}
   
  We also searched for similar issues and their solutions, and extracted the following information that is helpful for issue resolution:
  {refine_rag}

  INSTRUCTIONS:
  Now, you're going to solve this issue on your own from the perspective of a programmer. Your terminal session has started and you're in the repository's root directory. You can use any bash commands or the special interface to help you. Edit all the files you need. 
  Remember, YOU CAN ONLY ENTER ONE COMMAND AT A TIME. You should always wait for feedback after every command.
    
  Command Usage:
  1. Programmers have a multitude of commands at their disposal, which include not only general commands but also special ones. It's essential to carefully consider and select the most suitable command for each situation.
  2. If a command doesn't work, attempt a different command. A command that didn't work once is unlikely to work a second time without any modification.
  3. When you need to access a specific line in a file that's not within the first 100 lines, such as line 583, avoid using the scroll_down command repeatedly. Use the `goto 583` command instead for efficiency.
    
  Searching and Retrieving Information:
  1. Use the `related issue retrieval` command to search for a reference patch from a comparable issue.
  2. If you’re unsure about the exact line number when searching for a code snippet, class, or method within a file, prioritize using the `grep -nr <code/class/method>` command. This will help you find the approximate location. 

  Editing and File Navigation:
  1. When editing files, especially if you are executing the edit command multiple times on the same file, it's easy to run into syntax errors, such as incorrect indentation or specifying the wrong line number. Consider opening the file to view the surrounding code related to the error line and make modifications based on this context.
  2. Ensure to observe the currently open file and the current working directory, which is displayed right after the open file. The open file might be in a different directory than the working directory. Remember, commands like 'create' open files and might alter the current open file.
  3. When utilizing the `edit` command, ensure to remember that it operates within a closed range. This is crucial to prevent the accidental deletion of non-targeted code during the process of code replacement.
  4. When editing files, it is easy to accidentally specify a wrong line number or to write code with incorrect indentation. Always check the code after you issue an edit to make sure that it reflects what you wanted to accomplish. If it didn't, issue another command to fix it.
    
  Extracting Additional Project Context:
  1. If you need additional project context, such as related classes, methods, or code snippets, you can utilize one of the following commands to extract the required information.
   ```
   rover_search_file
   rover_search_class
   rover_search_class in file
   rover_search_method
   rover_search_method in file
   rover_search_code
   rover_search_code_in_file
   ```
    
  General Guideline:
  1. Always review your changes post-edit to ensure they accurately reflect your intentions. If the changes are not as desired, don't hesitate to issue another command to correct them.
    
  IMPORTANT TIPS:
  1. When editing a variable name, a argument type or a function signature, you should also propagate the changes based on its data and control dependence.
  2. When you use retrieval commands like `search_file`, `rover_search`, `search_dir` and so on, for multiple results retrieved, you must go through each search result, not just focus on the first one.
  3. Do not focus on the test files or files under the test directory of the project, especially the test files included in the search results. Also, do not execute the project's own tests other than 'reproduce.py'.
  4. When `reproduce.py` passes, you should consider whether the current fix is a minimal change. Do not delete code that is incompatible with your current issue.
  5. In addition, you should run the `reproduce.py` file after each successful modification if there is one. Do not modify the test code or `reproduce.py` code to avoid this issue. Your job is to edit the repository core code and resolve the issue. When analyzing an issue, you can focus on the parent classes and functions related to the library and locate the issue based on the call chain.
  6. Only return "succeed" command when the current task is truly completed. If the current task still cannot be completed after trying many different solutions, please return "fail" command.
    
  Please note that THE EDIT COMMAND REQUIRES PROPER INDENTATION. Pay attention to the original indentation when replacing the function. 
  In addition, you should run the `reproduce.py` file after each successful modification if there is one.
  When `reproduce.py` passes, you should consider whether the current fix is a minimal change. Do not delete code that is incompatible with your current issue.

multi_roles_transfer_template: |
  You are currently in a team organized by a manager, where each role has its own tasks. Everyone is working together to solve this issue. Here is some information about the team.
  {observation}
  
  As a Programmer, you must make good use of the context code searched and located from the `Debugger`, it can greatly help you to solve issues. Do not ignore information from other team members.
  
  CURRENT STATE
  (Open file: {open_file})
  (Current directory: {working_dir})
  bash-$
next_step_template: |-
  {observation}
  (Open file: {open_file})
  (Current directory: {working_dir})
  bash-$
next_step_no_output_template: |-
  Your command ran successfully and did not produce any output.
  (Open file: {open_file})
  (Current directory: {working_dir})
  bash-$
demonstration_template: |
  Here is a demonstration of how to correctly accomplish this task.
  It is included to show you how to correctly use the interface.
  You do not need to follow exactly what is done in the demonstration.
  --- DEMONSTRATION ---
  {demonstration}
  --- END OF DEMONSTRATION ---
state_command:
  name: state
  code: |
    state() {
      local working_dir="$PWD";
      if [ -z $CURRENT_FILE ]; then
          echo '{"open_file": "n/a", "working_dir": "'$working_dir'"}';
      else
          echo '{"open_file": "'$(realpath $CURRENT_FILE)'", "working_dir": "'$working_dir'"}';
      fi
    };
parse_function: ThoughtActionParser
env_variables:
  WINDOW: 100
  OVERLAP: 2
  CURRENT_LINE: 0
  CURRENT_FILE: ''
  SEARCH_RESULTS: ()
  SEARCH_FILES: ()
  SEARCH_INDEX: 0

command_files:
- config/commands/defaults.sh
- config/commands/search.sh
- config/commands/edit_linting.sh
- config/commands/_split_string.py
- config/commands/_augmented_rover_search.py
- config/commands/_similar_issue_retrieval.py
- config/commands/_web_issue_retrieval_with_api.py
- config/commands/similar_issue_retrieval.sh
- config/commands/search_stackoverflow.sh
- config/commands/rover_search

command_dependence:
- config/commands/retrieval_data
parse_command: ParseCommandDetailed
history_processor: DefaultHistoryProcessor
demonstrations:
  - trajectories/demonstrations/multi_roles/programmer_marshmallow-code__marshmallow-1867.traj